<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>haml</string>
	</array>
	<key>name</key>
	<string>Hamlpy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\s*- </string>
			<key>comment</key>
			<string>- tag</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>and|autoescape|as|block|blocktrans|comment|csrf_token|cycle|debug|extends|filter|firstof|for|from|empty|if|in|not|ifchanged|ifequal|ifnotequal|include|load|now|regroup|spaceless|ssi|trans|url|verbatim|widthradio|with</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string> 'key' : None</string>
			<key>match</key>
			<string>:\s*(None)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>hamlpy filter</string>
			<key>match</key>
			<string>^\s*:(plain|javascript|cdata|css|markdown|highlight|python)?$</string>
			<key>name</key>
			<string>entity.name.function.hamlpy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>doctypes</string>
			<key>match</key>
			<string>^\s*!!! (\s*(Frameset|Strict|5|1\.1|XML))?$</string>
			<key>name</key>
			<string>constant.numeric.hamlpy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(=|#|{){</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>{{ var|filter:'value' }}</string>
			<key>end</key>
			<string>}}?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[|:]</string>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(add|addslashs|capfirst|center|cut|date|default|default_if_none|dictsort|dictsortreversed|divisibleby|escape|escapejs|first|fix_ampersands|floatformat|force_escape|get_digit|iriencode|join|last|length|length_is|linebreaks|linebreaksbr|linenumbers|ljust|lower|make_list|phone2numeric|pluralize|pprint|random|removetags|rjust|safe|safeseq|slice|slugify|stringformat|striptags|time|timesince|timeuntil|title|truncatechars|truncatewords|truncatewords_html|unordered_list|upper|urlencode|urlize|urlizetrunc|wordcount|wordwrap|yesno|)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(((%)([a-z]+))|((#)([a-zA-Z0-9_-]+))|((\.)([a-zA-Z0-9_-]+)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.hamlpy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.hamlpy</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.language.hamlpy</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>%tag#id.class</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\s*$</string>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.hamlpy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.hamlpy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#)([a-zA-Z0-9_]+)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.hamlpy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.hamlpy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)([a-zA-Z0-9_]+)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.double.hamlpy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.hamlpy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>{% tags %}</string>
			<key>end</key>
			<string>%}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hamlpy</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>and|autoescape|as|block|blocktrans|comment|csrf_token|cycle|debug|extends|filter|firstof|for|from|empty|if|in|not|ifchanged|ifequal|ifnotequal|include|load|now|regroup|spaceless|ssi|trans|url|verbatim|widthradio|with</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(-#(.*)$)|^\s*/(.*)$</string>
			<key>name</key>
			<string>comment.line.hamlpy</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.hamlpy</string>
	<key>uuid</key>
	<string>963ae34b-a343-4921-81b6-4ad905ad7ae1</string>
</dict>
</plist>
